b_yexmygydxqxqygxuxnycxnxuxqxpxpyhygxoxqyfxqydxqxoxuydxuxmyhyhxuxuyjxrxuxrxpxrxmxp
b_xmxsyhydxnxlxtxuxmycxmxqxqxqxnxlygydycxnxmxrygxrxoxpxnyhyfyeyexoyjxrxuxrxpxrxmxp
b_ydxmxsxmycxryfyfxrygxmxpxqxlygyfyhyfxoydxoyfyeyhyfxnxqxnxlyeyfygyjxrxuxrxpxrxmxp
b_yfxsyfxnxtyexlxpyeyfxtxlxqxtxmyeygxnxlxnyfxlydycxqyeycyeygyextxqyjxrxuxrxpxrxmxp
b_xmxsydxsxoxsygxlyeyhyfydxqyfxlxpygxnxuxsydycxmxpycxsyeycxmyfxrxnyjxrxuxrxpxrxmxp
b_yhydxqxsydxqxnygxtxlxsxsxqxnyfyfygyfycxoydyfxtycxnxmxmxlxuxuydyhyjxrxuxrxpxrxmxp
